'use client'
import Navbar from '../../components/Navbar'
import { CartProvider } from '../../ctx/cartContext'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Navbar />
        {children}

        </CartProvider>
      </body>
    </html>
  )
}
